### ISSUE TITLE
Last Update Caused Blank Theme

### ISSUE THREAD

**Issue by flatlin-e** [AshPowell/monokai-one-dark-vivid-syntax#2]
The patch update today caused the theme to look like this:
![01-11-17 12-02-50pm](https://cloud.githubusercontent.com/assets/13840075/21864312/0fe72118-d7f6-11e6-9ba6-7b48d3220321.png)

**Comment by AshPowell** [comment]
ah no! what version of atom are you on? I'll have to make sure older versions are also supported... will try push an update before end of play tomorrow.. it should work with the latest atom version in the meantime

**Comment by flatlin-e** [comment]
I'm always up to date!

I'm on 1.12.9 - Windows

Tried restarting and everything

**Comment by AshPowell** [comment]
1.13 was released today... Try redownloading if nothing showing in atom itself.

**Comment by flatlin-e** [comment]
Had to re-download Atom and it's all fixed!

What a life saver (yes this theme is my life).

Haha, thank you! :)

**Comment by AshPowell** [comment]
Excellent, glad you got it sorted!
