### ISSUE TITLE
Blank Theme

### ISSUE THREAD

**Issue by flatlin-e** [AshPowell/monokai-one-dark-vivid-syntax#3]
Still on this theme after 3 years!

Last update caused the theme to go corrupt. Any fix to this?

**Atom version: 1.47.0**

![image](https://user-images.githubusercontent.com/13840075/82842183-6c228380-9e8d-11ea-9fd2-580579c1cf62.png)

**Comment by AshPowell** [comment]
I wish I had more time to upkeep this and keep the updates coming but unfortunately don't have much time lately.

I'm not experiencing the issue you are, can you double-check your language settings are set to HTML for that document?

**Comment by flatlin-e** [comment]
No worries! I just went back to 1.46.0 and it's amazing.
